### ISSUE TITLE
Buffs

### ISSUE THREAD

**Issue by JIMPZ** [XyzKangUI/Lorti-TBCC#1]
Problems with moving buffs/debuffs via config file.

**Comment by XyzKangUI** [comment]
> Problems with moving buffs/debuffs via config file.

That is because the config file no longer is the way to move buffs/debuffs. It functions like default BuffFrame now with just skinned icons. You can try move the BuffFrame using scripts, e.g. `BuffFrame:SetPoint("TOPRIGHT",` UIParent, "TOPRIGHT", -245, -115)`, or use an addon like Leatrix Plus / MoveAnything which allows you to move Buff Frames.
